"""Add custom_fields column to Task table

Revision ID: d64658587ac2
Revises: 
Create Date: 2025-03-04 20:23:13.269523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd64658587ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.String(length=200), nullable=True))
        batch_op.drop_column('custom_columns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_columns', sqlite.JSON(), nullable=True))
        batch_op.drop_column('custom_fields')

    # ### end Alembic commands ###
